compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  '@angular-builders/jest@*':
    peerDependenciesMeta:
      '@angular/platform-browser-dynamic':
        optional: true
  'jest-preset-angular@*':
    peerDependenciesMeta:
      '@angular/platform-browser-dynamic':
        optional: true

npmScopes:
  appreg:
    npmRegistryServer: 'https://pkgs.dev.azure.com/hmcts/Artifacts/_packaging/hmcts-lib/npm/registry/'
