sonar.projectName=appreg-frontend
sonar.projectKey=appreg-frontend
sonar.projectVersion=0.0.1

sonar.sources=src
sonar.exclusions=src/main.ts,src/main.server.ts,tools/openapi/**,src/**/openapi/**,src/**/generated/**

# Excludes certain files from coverage but still analyse them
sonar.coverage.exclusions=src/app/app.config.server.ts,src/app/app.routes.ts,src/app/app.routes.server.ts

sonar.tests=test
sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
