/**
 * Applications Register API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Status of the Application List.
 */
export enum ApplicationListStatus {

    OPEN = 'OPEN',

    CLOSED = 'CLOSED'
}

