/**
 * Applications Register API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicationListStatus } from './application-list-status';
import { CriminalJusticeAreaGetDto } from './criminal-justice-area-get-dto';
import { CourtLocationGetDetailDto } from './court-location-get-detail-dto';


/**
 * Request payload to create an Application List.
 */
export interface ApplicationListCreateDto { 
    date: string;
    time: string;
    description: string;
    status: ApplicationListStatus;
    courtLocation: CourtLocationGetDetailDto | null;
    /**
     * Free-text location if not using a standard court.
     */
    otherLocationDescription: string | null;
    criminalJusticeArea: CriminalJusticeAreaGetDto | null;
    durationHours?: number;
    durationMinutes?: number;
}



