/**
 * Applications Register API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicationListStatus } from './application-list-status';
import { CriminalJusticeAreaGetDto } from './criminal-justice-area-get-dto';
import { CourtLocationGetDetailDto } from './court-location-get-detail-dto';


/**
 * Request payload to fully replace an existing Application List.
 */
export interface ApplicationListUpdateDto { 
    /**
     * The calendar date on which the Application List is scheduled.
     */
    date: string;
    /**
     * The time of day at which the Application List is scheduled.
     */
    time: string;
    /**
     * Human-readable description of the Application List (e.g. session title or purpose).
     */
    description: string;
    status: ApplicationListStatus;
    courtLocation: CourtLocationGetDetailDto | null;
    /**
     * Free-text location if not using a standard court.
     */
    otherLocationDescription: string | null;
    criminalJusticeArea: CriminalJusticeAreaGetDto | null;
    /**
     * Duration hours component.
     */
    durationHours?: number;
    /**
     * Duration minutes component.
     */
    durationMinutes?: number;
    /**
     * Resource version for optimistic concurrency. Must match the current version on the server, otherwise the update will be rejected with 409 Conflict. 
     */
    version: number;
}



