/**
 * Applications Register API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MoneyGbp } from './money-gbp';

/**
 * Immutable DTO representing a detailed Application Code.
 */
export interface ApplicationCodeDto {
  /**
   * Code that identifies the application.
   */
  applicationCode: string;
  /**
   * Human-readable title.
   */
  title: string;
  /**
   * Full descriptive wording, potentially with blank fields to be inputted by the user.
   */
  wording: string;
  /**
   * True if Application List Entries using this Application Code require an Application List Entry Fee Status to be created and linked.
   */
  isFeeDue: boolean;
  /**
   * True if Application List Entries using this Application Code require a respondent to be created and linked.
   */
  requiresRespondent: boolean;
  /**
   * True if Application List Entries using this Application Code allow multiple respondents to be created and linked.
   */
  bulkRespondentAllowed: boolean;
  /**
   * A short reference code that identifies a Fee.
   */
  feeReference?: string | null;
  /**
   * Fee amount for this Application Code, expressed in pence (GBP minor units).
   */
  feeAmount?: MoneyGbp | null;
  /**
   * Descriptive text for the fee.
   */
  feeDescription?: string | null;
  /**
   * Offsite fee amount, expressed in pence (GBP minor units).
   */
  offsiteFeeAmount?: MoneyGbp | null;
}
