/**
 * Applications Register API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicationListStatus } from './application-list-status';


/**
 * Immutable DTO representing a summerised Application List.
 */
export interface ApplicationListGetSummaryDto { 
    /**
     * Unique identifier of the Application List.
     */
    id: string;
    /**
     * The calendar date on which the Application List is scheduled.
     */
    date: string;
    /**
     * The time of day at which the Application List is scheduled.
     */
    time: string;
    /**
     * Location where the applications will be considered.
     */
    location: string;
    /**
     * Human-readable description of the Application List (e.g. session title or purpose).
     */
    description: string;
    /**
     * Total number of Application List Entries associated with this Application List.
     */
    numberOfEntries: number;
    status: ApplicationListStatus;
}



