/**
 * Applications Register API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicationListStatus } from './application-list-status';
import { CriminalJusticeAreaGetDto } from './criminal-justice-area-get-dto';
import { CourtLocationGetDetailDto } from './court-location-get-detail-dto';


/**
 * Immutable DTO representing a detailed Application List.
 */
export interface ApplicationListGetDetailDto { 
    /**
     * Unique identifier of the Application List.
     */
    id: string;
    /**
     * The calendar date on which the Application List is scheduled.
     */
    date: string;
    /**
     * The time of day at which the Application List is scheduled.
     */
    time: string;
    /**
     * Human-readable description of the Application List (e.g. session title or purpose).
     */
    description: string;
    status: ApplicationListStatus;
    courtLocation: CourtLocationGetDetailDto | null;
    /**
     * Free-text location if not using a standard court.
     */
    otherLocationDescription: string | null;
    criminalJusticeArea: CriminalJusticeAreaGetDto | null;
    /**
     * Duration hours component.
     */
    durationHours?: number;
    /**
     * Duration minutes component.
     */
    durationMinutes?: number;
    /**
     * Current resource version for optimistic concurrency.
     */
    version: number;
}



