/**
 * Applications Register API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Fee amount for this Application Code, expressed in pence (GBP minor units). Always use integer values; 1 GBP = 100 pence. 
 */
export interface ApplicationCodeGetSummaryDtoFeeAmount { 
    /**
     * Amount in pence.
     */
    value: number;
    /**
     * ISO 4217 currency code (always \"GBP\" for now).
     */
    currency?: ApplicationCodeGetSummaryDtoFeeAmountCurrencyEnum;
}
export enum ApplicationCodeGetSummaryDtoFeeAmountCurrencyEnum {
    GBP = 'GBP'
};



