/**
 * Applications Register API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Immutable DTO representing a detailed Court Location.
 */
export interface CourtLocationGetDetailDto { 
    /**
     * Human-readable court name.
     */
    name: string;
    /**
     * Code that identifies the Court Location.
     */
    locationCode: string;
    /**
     * Date the Court Location became active.
     */
    startDate: string;
    /**
     * Date the Court Location became inactive. `null` indicates that this row is still active.
     */
    endDate: string | null;
}

