/**
 * Applications Register API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Immutable DTO representing a detailed Court Location.
 */
export interface CourtLocationDto { 
    /**
     * Human-readable court name.
     */
    name: string;
    /**
     * Code that identifies the Court Location.
     */
    locationCode: string;
}

