/**
 * Applications Register API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Immutable DTO representing a Criminal Justice Area.
 */
export interface CriminalJusticeAreaDto {
  /**
   * Code that identifies the Criminal Justice Area.
   */
  code: string;
  /**
   * Human-readable name of the Criminal Justice Area.
   */
  description: string;
}
