/**
 * Applications Register API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CriminalJusticeAreaDto } from './criminal-justice-area-dto';
import { Sort } from './sort';


export interface CriminalJusticeAreaPage { 
    content: Array<CriminalJusticeAreaDto>;
    /**
     * Zero-based page index.
     */
    pageNumber?: number;
    /**
     * Page size.
     */
    pageSize?: number;
    /**
     * Total number of elements across all pages.
     */
    totalElements: number;
    /**
     * Total number of pages.
     */
    totalPages: number;
    sort?: Sort;
    first?: boolean;
    last?: boolean;
    /**
     * Total number of elements in the current page.
     */
    elementsOnPage?: number;
}

