/**
 * Applications Register API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Monetary amount in GBP, expressed in pence (minor units). Always use integer values; 1 GBP = 100 pence.
 */
export interface MoneyGbp {
  /**
   * Amount in pence.
   */
  value: number;
  /**
   * ISO 4217 currency code (always \"GBP\" for now).
   */
  currency?: MoneyGbpCurrencyEnum;
}
export enum MoneyGbpCurrencyEnum {
  GBP = 'GBP',
}
