/**
 * Applications Register API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * RFC 9457/7807 problem details.
 */
export interface Problem { 
    /**
     * Problem type identifier (URI).
     */
    type: string;
    /**
     * Short, human-readable summary.
     */
    title: string;
    /**
     * HTTP status code.
     */
    status: number;
    /**
     * Human-readable explanation specific to this occurrence.
     */
    detail?: string;
    /**
     * URI reference to the specific occurrence (if applicable).
     */
    instance?: string;
    /**
     * Server-side correlation ID for tracing.
     */
    correlationId?: string;
}

