/**
 * Applications Register API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SortOrdersInner } from './sort-orders-inner';


/**
 * Sorting state for the returned page.
 */
export interface Sort { 
    /**
     * Active sort orders in priority order.
     */
    orders?: Array<SortOrdersInner>;
}

