/**
 * Applications Register API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface SortOrdersInner {
  /**
   * Property name used for sorting.
   */
  property: string;
  /**
   * Sort direction.
   */
  direction: SortOrdersInnerDirectionEnum;
}
export enum SortOrdersInnerDirectionEnum {
  ASC = 'asc',
  DESC = 'desc',
}
