/**
 * Applications Register API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StandardApplicantGetSummaryDto } from './standard-applicant-get-summary-dto';
import { Sort } from './sort';


export interface StandardApplicantPage { 
    /**
     * Zero-based page index.
     */
    pageNumber: number;
    /**
     * Page size.
     */
    pageSize: number;
    /**
     * Total number of elements across all pages.
     */
    totalElements: number;
    /**
     * Total number of pages.
     */
    totalPages?: number;
    sort?: Sort;
    first?: boolean;
    last?: boolean;
    /**
     * Total number of elements in the current page.
     */
    elementsOnPage: number;
    content: Array<StandardApplicantGetSummaryDto>;
}

