/**
 * Applications Register API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Immutable DTO representing a detailed Standard Applicant.
 */
export interface StandardApplicantDetailDto {
  /**
   * Code that identifies the Standard Applicant.
   */
  code: string;
  /**
   * Honorific prefix for a person’s name (e.g., Mr, Mrs, Ms, Dr, Prof).
   */
  title: string;
  /**
   * Full name of the applicant (may include forenames and surname).
   */
  name?: string;
  /**
   * First forename of the applicant.
   */
  forename1?: string;
  /**
   * Second forename of the applicant, if any.
   */
  forename2?: string;
  /**
   * Third forename of the applicant, if any.
   */
  forename3?: string;
  /**
   * Family name or last name of the applicant.
   */
  surname?: string;
  /**
   * First line of the applicant\'s address.
   */
  addressLine1: string;
  /**
   * Second line of the applicant\'s address.
   */
  addressLine2?: string;
  /**
   * Third line of the applicant\'s address.
   */
  addressLine3?: string;
  /**
   * Fourth line of the applicant\'s address.
   */
  addressLine4?: string;
  /**
   * Fifth line of the applicant\'s address.
   */
  addressLine5?: string;
  /**
   * Post code of the applicant\'s address.
   */
  postcode?: string;
  /**
   * Email address of the applicant.
   */
  emailAddress?: string;
  /**
   * Landline telephone number of the applicant.
   */
  telephoneNumber?: string;
  /**
   * Mobile phone number of the applicant.
   */
  mobileNumber?: string;
  /**
   * Date the applicant record became active.
   */
  startDate: string;
  /**
   * Date the applicant record became inactive (if applicable).
   */
  endDate: string | null;
}
