/**
 * Applications Register API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Lightweight DTO for Standard Applicants, used in list/search views.
 */
export interface StandardApplicantSummaryDto { 
    /**
     * Code that identifies the Standard Applicant.
     */
    code?: string;
    /**
     * Name of the Standard Applicant.
     */
    name?: string;
    /**
     * First line of the applicant\'s address.
     */
    addressLine1: string;
    /**
     * Date the applicant record became active.
     */
    startDate: string;
    /**
     * Date the applicant record became inactive (if applicable).
     */
    endDate: string | null;
}

