nodejs:
  applicationPort: 3000
  image: 'sdshmctspublic.azurecr.io/appreg/frontend:latest'
  ingressHost: appreg.{{ .Values.global.environment }}.apps.hmcts.net
  aadIdentityName: appreg
  readinessPeriod: 5
  terminationGracePeriodSeconds: 65
  keyVaults:
    appreg:
      secrets:
        - redis-connection-string
  environment:
    ALLOW_CONFIG_MUTATIONS: true
    APPREG_API_URL: https://appreg-api.{{ .Values.global.environment }}.platform.hmcts.net