/**
 * Applications Register API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApplicationListCreateDto } from '../model/models';
import { ApplicationListGetDetailDto } from '../model/models';
import { ApplicationListPage } from '../model/models';
import { ApplicationListStatus } from '../model/models';
import { ApplicationListUpdateDto } from '../model/models';
import { Problem } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CreateApplicationListRequestParams {
    applicationListCreateDto: ApplicationListCreateDto;
}

export interface DeleteApplicationListRequestParams {
    id: string;
}

export interface GetApplicationListRequestParams {
    id: string;
}

export interface ListApplicationListsRequestParams {
    dateFrom?: string;
    dateTo?: string;
    courtLocationCode?: string;
    status?: ApplicationListStatus;
    page?: number;
    size?: number;
    sort?: Array<string>;
}

export interface UpdateApplicationListRequestParams {
    id: string;
    applicationListUpdateDto: ApplicationListUpdateDto;
}


export interface ApplicationListsApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create an Application List
     * 
* @param requestParameters
     */
    createApplicationList(requestParameters: CreateApplicationListRequestParams, extraHttpRequestParams?: any): Observable<ApplicationListGetDetailDto>;

    /**
     * Delete an Application List
     * Permanently deletes the Application List identified by &#x60;id&#x60;.
* @param requestParameters
     */
    deleteApplicationList(requestParameters: DeleteApplicationListRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get an Application List by id
     * 
* @param requestParameters
     */
    getApplicationList(requestParameters: GetApplicationListRequestParams, extraHttpRequestParams?: any): Observable<ApplicationListGetDetailDto>;

    /**
     * Get Application Lists (paginated, filterable)
     * Returns a paginated list of Application Lists.
* @param requestParameters
     */
    listApplicationLists(requestParameters: ListApplicationListsRequestParams, extraHttpRequestParams?: any): Observable<ApplicationListPage>;

    /**
     * Update an Application List
     * Full replacement (PUT) of an existing Application List. The &#x60;id&#x60; is taken from the path; the request body must satisfy the same constraints as create (including the XOR location rule: either &#x60;courtLocation&#x60; or (&#x60;otherLocationDescription&#x60; + &#x60;criminalJusticeAreaCode&#x60;)). The request must include the current &#x60;version&#x60; for optimistic concurrency; a mismatch results in 409 Conflict. 
* @param requestParameters
     */
    updateApplicationList(requestParameters: UpdateApplicationListRequestParams, extraHttpRequestParams?: any): Observable<ApplicationListGetDetailDto>;

}
