/**
 * Applications Register API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApplicationCodeGetDetailDto } from '../model/models';
import { ApplicationCodePage } from '../model/models';
import { Problem } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface GetApplicationCodeByCodeAndDateRequestParams {
    code: string;
    date: string;
}

export interface GetApplicationCodesRequestParams {
    code?: string;
    title?: string;
    page?: number;
    size?: number;
    sort?: Array<string>;
}


export interface ApplicationCodesApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get a specific Application Code by code
     * 
* @param requestParameters
     */
    getApplicationCodeByCodeAndDate(requestParameters: GetApplicationCodeByCodeAndDateRequestParams, extraHttpRequestParams?: any): Observable<ApplicationCodeGetDetailDto>;

    /**
     * Get Application Codes (paginated, filterable)
     * Returns a paginated list of Application Codes. - Filters:   - &#x60;code&#x60; – case-insensitive partial match   - &#x60;title&#x60; – case-insensitive partial match 
* @param requestParameters
     */
    getApplicationCodes(requestParameters: GetApplicationCodesRequestParams, extraHttpRequestParams?: any): Observable<ApplicationCodePage>;

}
