/**
 * Applications Register API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { CourtLocationDto } from '../model/models';
import { Problem } from '../model/models';

import { Configuration } from '../configuration';

export interface GetCourtLocationByCodeAndDateRequestParams {
  code: string;
  date: string;
}

export interface CourtLocationApiInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   * Get a specific Court Location by code and date.
   *
   * @param requestParameters
   */
  getCourtLocationByCodeAndDate(
    requestParameters: GetCourtLocationByCodeAndDateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<CourtLocationDto>;
}
