/**
 * Applications Register API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { CourtLocationPage } from '../model/models';
import { Problem } from '../model/models';

import { Configuration } from '../configuration';

export interface GetCourtLocationsRequestParams {
  name?: string;
  code?: string;
  date?: string;
  page?: number;
  size?: number;
  sort?: Array<string>;
}

export interface CourtLocationsApiInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   * Get Court Locations (paginated, filterable)
   * Returns a paginated list of Court Locations. - Filters:   - &#x60;name&#x60; – case-insensitive partial match   - &#x60;code&#x60; – case-insensitive partial match   - &#x60;date&#x60; - a single ISO-8601 date (&#x60;yyyy-MM-dd&#x60;); returns records whose validity window includes that date. - Dates use ISO-8601 (yyyy-MM-dd).
   * @param requestParameters
   */
  getCourtLocations(
    requestParameters: GetCourtLocationsRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<CourtLocationPage>;
}
