/**
 * Applications Register API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CourtLocationGetDetailDto } from '../model/models';
import { CourtLocationPage } from '../model/models';
import { Problem } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface GetCourtLocationByCodeAndDateRequestParams {
    code: string;
    date: string;
}

export interface GetCourtLocationsRequestParams {
    name?: string;
    code?: string;
    page?: number;
    size?: number;
    sort?: Array<string>;
}


export interface CourtLocationsApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get a specific Court Location by code and date.
     * 
* @param requestParameters
     */
    getCourtLocationByCodeAndDate(requestParameters: GetCourtLocationByCodeAndDateRequestParams, extraHttpRequestParams?: any): Observable<CourtLocationGetDetailDto>;

    /**
     * Get Court Locations (paginated, filterable)
     * Returns a paginated list of Court Locations. - Filters:   - &#x60;name&#x60; – case-insensitive partial match   - &#x60;code&#x60; – case-insensitive partial match 
* @param requestParameters
     */
    getCourtLocations(requestParameters: GetCourtLocationsRequestParams, extraHttpRequestParams?: any): Observable<CourtLocationPage>;

}
