/**
 * Applications Register API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { CriminalJusticeAreaGetDto } from '../model/criminal-justice-area-get-dto';
// @ts-ignore
import { CriminalJusticeAreaPage } from '../model/criminal-justice-area-page';
// @ts-ignore
import { Problem } from '../model/problem';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';
import {
    CriminalJusticeAreasApiInterface,
    GetCriminalJusticeAreaByCodeRequestParams,
    GetCriminalJusticeAreasRequestParams
} from './criminal-justice-areas.serviceInterface';



@Injectable({
  providedIn: 'root'
})
export class CriminalJusticeAreasApi extends BaseService implements CriminalJusticeAreasApiInterface {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Get a specific Criminal Justice Area by code.
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCriminalJusticeAreaByCode(requestParameters: GetCriminalJusticeAreaByCodeRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.hmcts.appreg.v1+json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<CriminalJusticeAreaGetDto>;
    public getCriminalJusticeAreaByCode(requestParameters: GetCriminalJusticeAreaByCodeRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.hmcts.appreg.v1+json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<CriminalJusticeAreaGetDto>>;
    public getCriminalJusticeAreaByCode(requestParameters: GetCriminalJusticeAreaByCodeRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.hmcts.appreg.v1+json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<CriminalJusticeAreaGetDto>>;
    public getCriminalJusticeAreaByCode(requestParameters: GetCriminalJusticeAreaByCodeRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.hmcts.appreg.v1+json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const code = requestParameters?.code;
        if (code === null || code === undefined) {
            throw new Error('Required parameter code was null or undefined when calling getCriminalJusticeAreaByCode.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.hmcts.appreg.v1+json',
            'application/problem+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/criminal-justice-areas/${this.configuration.encodeParam({name: "code", value: code, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<CriminalJusticeAreaGetDto>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get Criminal Justice Areas (paginated, filterable)
     * Returns a paginated list of Criminal Justice Areas. - Filters:   - &#x60;code&#x60; – case-insensitive partial match.   - &#x60;description&#x60; – case-insensitive partial match. 
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCriminalJusticeAreas(requestParameters?: GetCriminalJusticeAreasRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.hmcts.appreg.v1+json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<CriminalJusticeAreaPage>;
    public getCriminalJusticeAreas(requestParameters?: GetCriminalJusticeAreasRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.hmcts.appreg.v1+json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<CriminalJusticeAreaPage>>;
    public getCriminalJusticeAreas(requestParameters?: GetCriminalJusticeAreasRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.hmcts.appreg.v1+json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<CriminalJusticeAreaPage>>;
    public getCriminalJusticeAreas(requestParameters?: GetCriminalJusticeAreasRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.hmcts.appreg.v1+json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const code = requestParameters?.code;
        const description = requestParameters?.description;
        const page = requestParameters?.page;
        const size = requestParameters?.size;
        const sort = requestParameters?.sort;

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>code, 'code');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>description, 'description');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>page, 'page');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>size, 'size');
        if (sort) {
            sort.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'sort');
            })
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.hmcts.appreg.v1+json',
            'application/problem+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/criminal-justice-areas`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<CriminalJusticeAreaPage>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

}
