/**
 * Applications Register API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { CriminalJusticeAreaDto } from '../model/models';
import { CriminalJusticeAreaPage } from '../model/models';
import { Problem } from '../model/models';

import { Configuration } from '../configuration';

export interface GetCriminalJusticeAreaByCodeRequestParams {
  code: string;
}

export interface GetCriminalJusticeAreasRequestParams {
  code?: string;
  description?: string;
  page?: number;
  size?: number;
  sort?: Array<string>;
}

export interface CriminalJusticeAreasApiInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   * Get a specific Criminal Justice Area by code.
   *
   * @param requestParameters
   */
  getCriminalJusticeAreaByCode(
    requestParameters: GetCriminalJusticeAreaByCodeRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<CriminalJusticeAreaDto>;

  /**
   * Get Criminal Justice Areas (paginated, filterable)
   * Returns a paginated list of Criminal Justice Areas. - Filters:   - &#x60;code&#x60; – case-insensitive partial match.   - &#x60;description&#x60; – case-insensitive partial match.
   * @param requestParameters
   */
  getCriminalJusticeAreas(
    requestParameters: GetCriminalJusticeAreasRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<CriminalJusticeAreaPage>;
}
