/**
 * Applications Register API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Problem } from '../model/models';
import { StandardApplicantDetailDto } from '../model/models';
import { StandardApplicantPage } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface GetStandardApplicantByCodeAndDateRequestParams {
    code: string;
    date: string;
}

export interface GetStandardApplicantsRequestParams {
    code?: string;
    title?: string;
    date?: string;
    page?: number;
    size?: number;
    sort?: Array<string>;
}


export interface StandardApplicantsApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get a specific Standard Applicant by code and date.
     * 
* @param requestParameters
     */
    getStandardApplicantByCodeAndDate(requestParameters: GetStandardApplicantByCodeAndDateRequestParams, extraHttpRequestParams?: any): Observable<StandardApplicantDetailDto>;

    /**
     * Get Standard Applicants (paginated, filterable)
     * Returns a paginated list of Standard Applicants. - Filters:   - &#x60;code&#x60; – case-insensitive partial match   - &#x60;name&#x60; – case-insensitive partial match   - &#x60;date&#x60; - a single ISO-8601 date (&#x60;yyyy-MM-dd&#x60;); returns records whose validity window includes that date. - Dates use ISO-8601 (yyyy-MM-dd). 
* @param requestParameters
     */
    getStandardApplicants(requestParameters: GetStandardApplicantsRequestParams, extraHttpRequestParams?: any): Observable<StandardApplicantPage>;

}
