/**
 * Applications Register API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { Problem } from '../model/problem';
// @ts-ignore
import { StandardApplicantGetDetailDto } from '../model/standard-applicant-get-detail-dto';
// @ts-ignore
import { StandardApplicantPage } from '../model/standard-applicant-page';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';
import {
    StandardApplicantsApiInterface,
    GetStandardApplicantByCodeAndDateRequestParams,
    GetStandardApplicantsRequestParams
} from './standard-applicants.serviceInterface';



@Injectable({
  providedIn: 'root'
})
export class StandardApplicantsApi extends BaseService implements StandardApplicantsApiInterface {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Get a specific Standard Applicant by code and date.
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getStandardApplicantByCodeAndDate(requestParameters: GetStandardApplicantByCodeAndDateRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.hmcts.appreg.v1+json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<StandardApplicantGetDetailDto>;
    public getStandardApplicantByCodeAndDate(requestParameters: GetStandardApplicantByCodeAndDateRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.hmcts.appreg.v1+json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<StandardApplicantGetDetailDto>>;
    public getStandardApplicantByCodeAndDate(requestParameters: GetStandardApplicantByCodeAndDateRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.hmcts.appreg.v1+json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<StandardApplicantGetDetailDto>>;
    public getStandardApplicantByCodeAndDate(requestParameters: GetStandardApplicantByCodeAndDateRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.hmcts.appreg.v1+json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const code = requestParameters?.code;
        if (code === null || code === undefined) {
            throw new Error('Required parameter code was null or undefined when calling getStandardApplicantByCodeAndDate.');
        }
        const date = requestParameters?.date;
        if (date === null || date === undefined) {
            throw new Error('Required parameter date was null or undefined when calling getStandardApplicantByCodeAndDate.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>date, 'date');

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.hmcts.appreg.v1+json',
            'application/problem+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/standard-applicants/${this.configuration.encodeParam({name: "code", value: code, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<StandardApplicantGetDetailDto>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get Standard Applicants (paginated, filterable)
     * Returns a paginated list of Standard Applicants. - Filters:   - &#x60;code&#x60; – case-insensitive partial match   - &#x60;name&#x60; – case-insensitive partial match 
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getStandardApplicants(requestParameters?: GetStandardApplicantsRequestParams, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.hmcts.appreg.v1+json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<StandardApplicantPage>;
    public getStandardApplicants(requestParameters?: GetStandardApplicantsRequestParams, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.hmcts.appreg.v1+json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<StandardApplicantPage>>;
    public getStandardApplicants(requestParameters?: GetStandardApplicantsRequestParams, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/vnd.hmcts.appreg.v1+json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<StandardApplicantPage>>;
    public getStandardApplicants(requestParameters?: GetStandardApplicantsRequestParams, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/vnd.hmcts.appreg.v1+json' | 'application/problem+json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        const code = requestParameters?.code;
        const title = requestParameters?.title;
        const page = requestParameters?.page;
        const size = requestParameters?.size;
        const sort = requestParameters?.sort;

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>code, 'code');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>title, 'title');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>page, 'page');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>size, 'size');
        if (sort) {
            sort.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'sort');
            })
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/vnd.hmcts.appreg.v1+json',
            'application/problem+json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/standard-applicants`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<StandardApplicantPage>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

}
